const COUNTRY = [
  { id: "AD", value: "Andorra", phone: "376" },
  { id: "AE", value: "United Arab Emirates", phone: "971" },
  { id: "AF", value: "Afghanistan", phone: "93" },
  { id: "AG", value: "Antigua and Barbuda", phone: "1-268" },
  { id: "AI", value: "Anguilla", phone: "1-264" },
  { id: "AL", value: "Albania", phone: "355" },
  { id: "AM", value: "Armenia", phone: "374" },
  { id: "AO", value: "Angola", phone: "244" },
  { id: "AQ", value: "Antarctica", phone: "672" },
  { id: "AR", value: "Argentina", phone: "54" },
  { id: "AS", value: "American Samoa", phone: "1-684" },
  { id: "AT", value: "Austria", phone: "43" },
  { id: "AU", value: "Australia", phone: "61", suggested: true },
  { id: "AW", value: "Aruba", phone: "297" },
  { id: "AX", value: "Alland Islands", phone: "358" },
  { id: "AZ", value: "Azerbaijan", phone: "994" },
  { id: "BA", value: "Bosnia and Herzegovina", phone: "387" },
  { id: "BB", value: "Barbados", phone: "1-246" },
  { id: "BD", value: "Bangladesh", phone: "880" },
  { id: "BE", value: "Belgium", phone: "32" },
  { id: "BF", value: "Burkina Faso", phone: "226" },
  { id: "BG", value: "Bulgaria", phone: "359" },
  { id: "BH", value: "Bahrain", phone: "973" },
  { id: "BI", value: "Burundi", phone: "257" },
  { id: "BJ", value: "Benin", phone: "229" },
  { id: "BL", value: "Saint Barthelemy", phone: "590" },
  { id: "BM", value: "Bermuda", phone: "1-441" },
  { id: "BN", value: "Brunei Darussalam", phone: "673" },
  { id: "BO", value: "Bolivia", phone: "591" },
  { id: "BR", value: "Brazil", phone: "55" },
  { id: "BS", value: "Bahamas", phone: "1-242" },
  { id: "BT", value: "Bhutan", phone: "975" },
  { id: "BV", value: "Bouvet Island", phone: "47" },
  { id: "BW", value: "Botswana", phone: "267" },
  { id: "BY", value: "Belarus", phone: "375" },
  { id: "BZ", value: "Belize", phone: "501" },
  { id: "CA", value: "Canada", phone: "1", suggested: true },
  { id: "CC", value: "Cocos (Keeling) Islands", phone: "61" },
  { id: "CD", value: "Congo, Democratic Republic of the", phone: "243" },
  { id: "CF", value: "Central African Republic", phone: "236" },
  { id: "CG", value: "Congo, Republic of the", phone: "242" },
  { id: "CH", value: "Switzerland", phone: "41" },
  { id: "CI", value: "Cote d'Ivoire", phone: "225" },
  { id: "CK", value: "Cook Islands", phone: "682" },
  { id: "CL", value: "Chile", phone: "56" },
  { id: "CM", value: "Cameroon", phone: "237" },
  { id: "CN", value: "China", phone: "86" },
  { id: "CO", value: "Colombia", phone: "57" },
  { id: "CR", value: "Costa Rica", phone: "506" },
  { id: "CU", value: "Cuba", phone: "53" },
  { id: "CV", value: "Cape Verde", phone: "238" },
  { id: "CW", value: "Curacao", phone: "599" },
  { id: "CX", value: "Christmas Island", phone: "61" },
  { id: "CY", value: "Cyprus", phone: "357" },
  { id: "CZ", value: "Czech Republic", phone: "420" },
  { id: "DE", value: "Germany", phone: "49", suggested: true },
  { id: "DJ", value: "Djibouti", phone: "253" },
  { id: "DK", value: "Denmark", phone: "45" },
  { id: "DM", value: "Dominica", phone: "1-767" },
  { id: "DO", value: "Dominican Republic", phone: "1-809" },
  { id: "DZ", value: "Algeria", phone: "213" },
  { id: "EC", value: "Ecuador", phone: "593" },
  { id: "EE", value: "Estonia", phone: "372" },
  { id: "EG", value: "Egypt", phone: "20" },
  { id: "EH", value: "Western Sahara", phone: "212" },
  { id: "ER", value: "Eritrea", phone: "291" },
  { id: "ES", value: "Spain", phone: "34" },
  { id: "ET", value: "Ethiopia", phone: "251" },
  { id: "FI", value: "Finland", phone: "358" },
  { id: "FJ", value: "Fiji", phone: "679" },
  { id: "FK", value: "Falkland Islands (Malvinas)", phone: "500" },
  { id: "FM", value: "Micronesia, Federated States of", phone: "691" },
  { id: "FO", value: "Faroe Islands", phone: "298" },
  { id: "FR", value: "France", phone: "33", suggested: true },
  { id: "GA", value: "Gabon", phone: "241" },
  { id: "GB", value: "United Kingdom", phone: "44" },
  { id: "GD", value: "Grenada", phone: "1-473" },
  { id: "GE", value: "Georgia", phone: "995" },
  { id: "GF", value: "French Guiana", phone: "594" },
  { id: "GG", value: "Guernsey", phone: "44" },
  { id: "GH", value: "Ghana", phone: "233" },
  { id: "GI", value: "Gibraltar", phone: "350" },
  { id: "GL", value: "Greenland", phone: "299" },
  { id: "GM", value: "Gambia", phone: "220" },
  { id: "GN", value: "Guinea", phone: "224" },
  { id: "GP", value: "Guadeloupe", phone: "590" },
  { id: "GQ", value: "Equatorial Guinea", phone: "240" },
  { id: "GR", value: "Greece", phone: "30" },
  { id: "GS", value: "South Georgia and the South Sandwich Islands", phone: "500" },
  { id: "GT", value: "Guatemala", phone: "502" },
  { id: "GU", value: "Guam", phone: "1-671" },
  { id: "GW", value: "Guinea-Bissau", phone: "245" },
  { id: "GY", value: "Guyana", phone: "592" },
  { id: "HK", value: "Hong Kong", phone: "852" },
  { id: "HM", value: "Heard Island and McDonald Islands", phone: "672" },
  { id: "HN", value: "Honduras", phone: "504" },
  { id: "HR", value: "Croatia", phone: "385" },
  { id: "HT", value: "Haiti", phone: "509" },
  { id: "HU", value: "Hungary", phone: "36" },
  { id: "ID", value: "Indonesia", phone: "62" },
  { id: "IE", value: "Ireland", phone: "353" },
  { id: "IL", value: "Israel", phone: "972" },
  { id: "IM", value: "Isle of Man", phone: "44" },
  { id: "IN", value: "India", phone: "91" },
  { id: "IO", value: "British Indian Ocean Territory", phone: "246" },
  { id: "IQ", value: "Iraq", phone: "964" },
  { id: "IR", value: "Iran, Islamic Republic of", phone: "98" },
  { id: "IS", value: "Iceland", phone: "354" },
  { id: "IT", value: "Italy", phone: "39" },
  { id: "JE", value: "Jersey", phone: "44" },
  { id: "JM", value: "Jamaica", phone: "1-876" },
  { id: "JO", value: "Jordan", phone: "962" },
  { id: "JP", value: "Japan", phone: "81", suggested: true },
  { id: "KE", value: "Kenya", phone: "254" },
  { id: "KG", value: "Kyrgyzstan", phone: "996" },
  { id: "KH", value: "Cambodia", phone: "855" },
  { id: "KI", value: "Kiribati", phone: "686" },
  { id: "KM", value: "Comoros", phone: "269" },
  { id: "KN", value: "Saint Kitts and Nevis", phone: "1-869" },
  { id: "KP", value: "Korea, Democratic People's Republic of", phone: "850" },
  { id: "KR", value: "Korea, Republic of", phone: "82" },
  { id: "KW", value: "Kuwait", phone: "965" },
  { id: "KY", value: "Cayman Islands", phone: "1-345" },
  { id: "KZ", value: "Kazakhstan", phone: "7" },
  { id: "LA", value: "Lao People's Democratic Republic", phone: "856" },
  { id: "LB", value: "Lebanon", phone: "961" },
  { id: "LC", value: "Saint Lucia", phone: "1-758" },
  { id: "LI", value: "Liechtenstein", phone: "423" },
  { id: "LK", value: "Sri Lanka", phone: "94" },
  { id: "LR", value: "Liberia", phone: "231" },
  { id: "LS", value: "Lesotho", phone: "266" },
  { id: "LT", value: "Lithuania", phone: "370" },
  { id: "LU", value: "Luxembourg", phone: "352" },
  { id: "LV", value: "Latvia", phone: "371" },
  { id: "LY", value: "Libya", phone: "218" },
  { id: "MA", value: "Morocco", phone: "212" },
  { id: "MC", value: "Monaco", phone: "377" },
  { id: "MD", value: "Moldova, Republic of", phone: "373" },
  { id: "ME", value: "Montenegro", phone: "382" },
  { id: "MF", value: "Saint Martin (French part)", phone: "590" },
  { id: "MG", value: "Madagascar", phone: "261" },
  { id: "MH", value: "Marshall Islands", phone: "692" },
  { id: "MK", value: "Macedonia, the Former Yugoslav Republic of", phone: "389" },
  { id: "ML", value: "Mali", phone: "223" },
  { id: "MM", value: "Myanmar", phone: "95" },
  { id: "MN", value: "Mongolia", phone: "976" },
  { id: "MO", value: "Macao", phone: "853" },
  { id: "MP", value: "Northern Mariana Islands", phone: "1-670" },
  { id: "MQ", value: "Martinique", phone: "596" },
  { id: "MR", value: "Mauritania", phone: "222" },
  { id: "MS", value: "Montserrat", phone: "1-664" },
  { id: "MT", value: "Malta", phone: "356" },
  { id: "MU", value: "Mauritius", phone: "230" },
  { id: "MV", value: "Maldives", phone: "960" },
  { id: "MW", value: "Malawi", phone: "265" },
  { id: "MX", value: "Mexico", phone: "52" },
  { id: "MY", value: "Malaysia", phone: "60" },
  { id: "MZ", value: "Mozambique", phone: "258" },
  { id: "NA", value: "Namibia", phone: "264" },
  { id: "NC", value: "New Caledonia", phone: "687" },
  { id: "NE", value: "Niger", phone: "227" },
  { id: "NF", value: "Norfolk Island", phone: "672" },
  { id: "NG", value: "Nigeria", phone: "234" },
  { id: "NI", value: "Nicaragua", phone: "505" },
  { id: "NL", value: "Netherlands", phone: "31" },
  { id: "NO", value: "Norway", phone: "47" },
  { id: "NP", value: "Nepal", phone: "977" },
  { id: "NR", value: "Nauru", phone: "674" },
  { id: "NU", value: "Niue", phone: "683" },
  { id: "NZ", value: "New Zealand", phone: "64" },
  { id: "OM", value: "Oman", phone: "968" },
  { id: "PA", value: "Panama", phone: "507" },
  { id: "PE", value: "Peru", phone: "51" },
  { id: "PF", value: "French Polynesia", phone: "689" },
  { id: "PG", value: "Papua New Guinea", phone: "675" },
  { id: "PH", value: "Philippines", phone: "63" },
  { id: "PK", value: "Pakistan", phone: "92" },
  { id: "PL", value: "Poland", phone: "48" },
  { id: "PM", value: "Saint Pierre and Miquelon", phone: "508" },
  { id: "PN", value: "Pitcairn", phone: "870" },
  { id: "PR", value: "Puerto Rico", phone: "1" },
  { id: "PS", value: "Palestine, State of", phone: "970" },
  { id: "PT", value: "Portugal", phone: "351" },
  { id: "PW", value: "Palau", phone: "680" },
  { id: "PY", value: "Paraguay", phone: "595" },
  { id: "QA", value: "Qatar", phone: "974" },
  { id: "RE", value: "Reunion", phone: "262" },
  { id: "RO", value: "Romania", phone: "40" },
  { id: "RS", value: "Serbia", phone: "381" },
  { id: "RU", value: "Russian Federation", phone: "7" },
  { id: "RW", value: "Rwanda", phone: "250" },
  { id: "SA", value: "Saudi Arabia", phone: "966" },
  { id: "SB", value: "Solomon Islands", phone: "677" },
  { id: "SC", value: "Seychelles", phone: "248" },
  { id: "SD", value: "Sudan", phone: "249" },
  { id: "SE", value: "Sweden", phone: "46" },
  { id: "SG", value: "Singapore", phone: "65" },
  { id: "SH", value: "Saint Helena", phone: "290" },
  { id: "SI", value: "Slovenia", phone: "386" },
  { id: "SJ", value: "Svalbard and Jan Mayen", phone: "47" },
  { id: "SK", value: "Slovakia", phone: "421" },
  { id: "SL", value: "Sierra Leone", phone: "232" },
  { id: "SM", value: "San Marino", phone: "378" },
  { id: "SN", value: "Senegal", phone: "221" },
  { id: "SO", value: "Somalia", phone: "252" },
  { id: "SR", value: "Suriname", phone: "597" },
  { id: "SS", value: "South Sudan", phone: "211" },
  { id: "ST", value: "Sao Tome and Principe", phone: "239" },
  { id: "SV", value: "El Salvador", phone: "503" },
  { id: "SX", value: "Sint Maarten (Dutch part)", phone: "1-721" },
  { id: "SY", value: "Syrian Arab Republic", phone: "963" },
  { id: "SZ", value: "Swaziland", phone: "268" },
  { id: "TC", value: "Turks and Caicos Islands", phone: "1-649" },
  { id: "TD", value: "Chad", phone: "235" },
  { id: "TF", value: "French Southern Territories", phone: "262" },
  { id: "TG", value: "Togo", phone: "228" },
  { id: "TH", value: "Thailand", phone: "66" },
  { id: "TJ", value: "Tajikistan", phone: "992" },
  { id: "TK", value: "Tokelau", phone: "690" },
  { id: "TL", value: "Timor-Leste", phone: "670" },
  { id: "TM", value: "Turkmenistan", phone: "993" },
  { id: "TN", value: "Tunisia", phone: "216" },
  { id: "TO", value: "Tonga", phone: "676" },
  { id: "TR", value: "Turkey", phone: "90" },
  { id: "TT", value: "Trinidad and Tobago", phone: "1-868" },
  { id: "TV", value: "Tuvalu", phone: "688" },
  { id: "TW", value: "Taiwan, Province of China", phone: "886" },
  { id: "TZ", value: "United Republic of Tanzania", phone: "255" },
  { id: "UA", value: "Ukraine", phone: "380" },
  { id: "UG", value: "Uganda", phone: "256" },
  { id: "US", value: "United States", phone: "1", suggested: true },
  { id: "UY", value: "Uruguay", phone: "598" },
  { id: "UZ", value: "Uzbekistan", phone: "998" },
  { id: "VA", value: "Holy See (Vatican City State)", phone: "379" },
  { id: "VC", value: "Saint Vincent and the Grenadines", phone: "1-784" },
  { id: "VE", value: "Venezuela", phone: "58" },
  { id: "VG", value: "British Virgin Islands", phone: "1-284" },
  { id: "VI", value: "US Virgin Islands", phone: "1-340" },
  { id: "VN", value: "Vietnam", phone: "84" },
  { id: "VU", value: "Vanuatu", phone: "678" },
  { id: "WF", value: "Wallis and Futuna", phone: "681" },
  { id: "WS", value: "Samoa", phone: "685" },
  { id: "XK", value: "Kosovo", phone: "383" },
  { id: "YE", value: "Yemen", phone: "967" },
  { id: "YT", value: "Mayotte", phone: "262" },
  { id: "ZA", value: "South Africa", phone: "27" },
  { id: "ZM", value: "Zambia", phone: "260" },
  { id: "ZW", value: "Zimbabwe", phone: "263" },
];

export { COUNTRY };
